generatorName: typescript-node
typeMappings: {}
additionalProperties:
  npmName: "hellosign-sdk"
  npmVersion: 6.0.0-beta22.24
  gitUserId: HelloFax
  gitRepoId: hellosign-nodejs-sdk
  supportsES6: true
  apiDocPath: ./docs/api
  modelDocPath: ./docs/model
  sortModelPropertiesByRequiredFlag: true
files:
  npmignore:
    templateType: SupportingFiles
    destinationFilename: .npmignore
  api-doc.mustache:
    templateType: APIDocs
    destinationFilename: .md
  model-doc.mustache:
    templateType: ModelDocs
    destinationFilename: .md
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
  eventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: model/eventCallbackHelper.ts
globalProperties:
  apiTests: false
  modelTests: false
